### ISSUE TITLE
Can't find Websocket client

### ISSUE THREAD

**Issue by AlexDias79** [hprose/hprose-dotnet#13]
Hello guys,

I've been using the hprose WebSocketService() for Go for some time but I couldn't find a way to use it with the dotnet client. Is there any way to do this?

**Comment by andot** [comment]
There is no websocket client in hprose,  but you can use http client instead.

**Comment by AlexDias79** [comment]
Too bad, I was looking for an easy way to get notifactions/events  using the socket chan. Correct me if I'm wrong but Http Client won't do it since I would need it to be Async.

**Comment by andot** [comment]
The hprose for .net has not been update to 2.0 version, so pub/sub has not been implemented yet. We will add this feature in hprose 2.0 for .net.

**Comment by AlexDias79** [comment]
Can't wait for it :)
Thanks for the reply though

**Comment by Disturbing** [comment]
@andot - Any timeline for the 2.0 version?  I may be able to help and in Hong Kong at the moment.

**Comment by andot** [comment]
There is no timeline for the 2.0 version of hprose for .NET.

**Comment by andot** [comment]
Hprose 3.0 for .NET is out now.
