### ISSUE TITLE
.net根据hprose服务方法名查询相关信息

### ISSUE THREAD

**Issue by WildShooter** [hprose/hprose-dotnet#15]
在已知服务方法名的基础上，根据方法名获取服务方法所在的类对象，类型，该方法对应的Attribute的对象信息

**Comment by andot** [comment]
好的，记下来，2.0 的时候加上这个功能。

**Comment by andot** [comment]
3.0 中可以通过 Service.Get 方法来获取，参数是方法名和参数个数（参数个数计数不包含Context参数在内）
