### ISSUE TITLE
.Net版本DataTable支持

### ISSUE THREAD

**Issue by Herryo0O** [hprose/hprose-dotnet#17]
下面是Write和Read方法，主要是將DataTable轉ObjectArray，在ObjectArray中用xml保存了DataTable的定義，這樣做使用沒有問題，速度目前也還行，但是畢竟多了一次DataTable與ObjectArray的轉換，不夠原生，不清楚有沒有更好更直接的方法？

        public void WriteDataTableWithRef(DataTable dt) {
            if (string.IsNullOrWhiteSpace(dt.TableName))
                dt.TableName = "DataTable";

            int k = 0;
            int r = dt.Rows.Count;
            int c = dt.Columns.Count;
            object[] o = new object[r * c + 3];

            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            System.Xml.XmlWriter writer = System.Xml.XmlWriter.Create(sb);
            System.Xml.Serialization.XmlSerializer serializer = new System.Xml.Serialization.XmlSerializer(typeof(DataTable));
            serializer.Serialize(writer, dt.Clone());
            writer.Close();

            o[k] = r;
            k = k + 1;
            o[k] = c;
            k = k + 1;
            o[k] = sb;
            k = k + 1;

            for (int i = 0; i < r; i++)
            {
                for (int j = 0; j < c; j++)
                {
                    o[k] = dt.Rows[i][j];
                    k = k + 1;
                }
            }       

            if (!refer.Write(o)) WriteArray(o);
        }

        public DataTable ReadDataTable() {
            object[] o = ReadObjectArray();
            
            int k = 0;
            int r = int.Parse(o[k].ToString());
            k = k + 1;
            int c = int.Parse(o[k].ToString());
            k = k + 1;

            System.IO.StringReader strReader = new System.IO.StringReader(o[k].ToString());
            System.Xml.XmlReader xmlReader = System.Xml.XmlReader.Create(strReader);
            System.Xml.Serialization.XmlSerializer serializer = new System.Xml.Serialization.XmlSerializer(typeof(DataTable));
            DataTable dt = serializer.Deserialize(xmlReader) as DataTable;
            k = k + 1;

            for (int i = 0; i < r; i++)
            {
                DataRow dr = dt.NewRow();
                for (int j = 0; j < c; j++)
                {
                    dr[j] = o[k];
                    k = k + 1;
                }
                dt.Rows.Add(dr);
            }
            dt.AcceptChanges();
            return dt;
        }

**Comment by andot** [comment]
你已经用xml序列化了整个DataTable了，好像就不需要再把每个值都序列化一遍了吧。

**Comment by Herryo0O** [comment]
serializer.Serialize(writer, dt.Clone());
xml只要了結構，沒有要數據。

**Comment by Herryo0O** [comment]
我的想法是這裡的xml類似Hprose中類型的Tag，後面跟着是數據，只是我試了一下原生的寫法，但是不會。只好先全部放ObjectArray在用你有的方法序列化。

**Comment by andot** [comment]
Hprose 3.0 已经增加了 Datatable 和 Dataset 的序列化支持，而且还可以跟其它语言互通了。
