### ISSUE TITLE
跨源请求问题

### ISSUE THREAD

**Issue by jeffreylau7** [hprose/hprose-dotnet#19]
服务端用dotnet版本，客户端用html5版本
服务端设置 ： “IsCrossDomainEnabled = true;”
客户端还是提示禁止访问资源，CORS 头缺少 'Access-Control-Allow-Origin'。
请问如何解决？

**Comment by andot** [comment]
就是这样设置，你检查一下是不是你的其它设置把这个头给吞了。

**Comment by jeffreylau7** [comment]
谢谢！我查看一下
