### ISSUE TITLE
支持 .Net Core 2.0 吗？

### ISSUE THREAD

**Issue by Herryo0O** [hprose/hprose-dotnet#26]
支持 .Net Core 2.0 吗？

**Comment by andot** [comment]
支持，目前 1.5.8 版本里面有 .NET Core 2.0 的项目工程和编译好的dll。

**Comment by Herryo0O** [comment]
小马哥真帅，好期待！


来自 魅族 PRO 5

-------- 原始邮件 --------
发件人：小马哥 <notifications@github.com>
时间：周日 3月18日 12:08
收件人：hprose/hprose-dotnet <hprose-dotnet@noreply.github.com>
抄送：Herryo0O <ccwangz@qq.com>,Author <author@noreply.github.com>
主题：Re: [hprose/hprose-dotnet] 支持 .Net Core 2.0 吗？ (#26)

**Comment by andot** [comment]
3.0 版本已经出来了。支持 .NET Core 2.0、2.1、2.2。 .NET Core 3.0 发布之后，也会支持 .NET Core 3.0 的。
