### ISSUE TITLE
请问推送功能性能

### ISSUE THREAD

**Issue by zhusheping** [hprose/hprose-dotnet#28]
订阅的Client是通过Socket与Server建立连接的吗？Server的一个端口大约可以支持多少个Client订阅

**Comment by andot** [comment]
.NET 版本的推送功能还没实现呢。支持多少个客户端跟你服务器的CPU和内存有关，到时候你要自己实测过才知道。

**Comment by andot** [comment]
3.0 版本已经出来了，你可以测试一下了。现在的 3.0 版本比其它语言 2.0 版本的推送功能更强，性能也更好更稳定。
