### ISSUE TITLE
请问andot大神, C#的2.0版本有时间计划表吗?最近两三个月能出来吗?

### ISSUE THREAD

**Issue by Yang8021** [hprose/hprose-dotnet#29]

**Comment by andot** [comment]
我需要一台新电脑才能继续开发，现在的电脑因为机械硬盘太慢了，导致打开 VS 需要很长时间，写代码还很容易崩溃，但是现在没工作，所以没钱换，看啥时候有钱再说吧。

**Comment by sgf** [comment]
@andot 买块ssd 啊 秋名山的 很便宜，199元 240G TLC的。性能够用了。
话说  其实现在应该放眼 .net core 2.1,2.2,3.0 了

**Comment by andot** [comment]
我现在的机器是 iMac 顶配，3T 的 Fusion Drive，没有办法换硬盘啊。

**Comment by sgf** [comment]
那就没办法了。毕竟iMac 太昂贵了 如果没法换硬盘的话。换台机器的成本那是相当高 😂
只能 继续用相当长一段时间 的1.58版本了。
话说 Hprose 2.0 ， Hprose 3.0 这些有标准文档吗？

**Comment by andot** [comment]
2.0 的标准文档在 https://github.com/hprose/hprose 这个项目中。3.0 的内容在它的 issues 讨论中。这两天正在筹备买电脑的钱。

**Comment by andot** [comment]
Hprose 3.0 已完成，现已合并到主分支了。
