### ISSUE TITLE
设置接收数据的编码格式问题

### ISSUE THREAD

**Issue by hdzs** [hprose/hprose-dotnet#31]
AcceptEncoding设置编码格式好像没有生效。接口返回数据包含utf8mb4格式字符串，未进行任何设置时报错提示“bad utf-8 encoding at 0xf0”，然而设置AcceptEncoding设置任何其他编码格式，仍然提示该错误

**Comment by andot** [comment]
AcceptEncoding 是用来设置压缩编码格式的，跟文本编码格式没关系。而且 hprose 只支持 utf8（utf8mb4），不需要设置。
