### ISSUE TITLE
3.0版本如何编译成dll

### ISSUE THREAD

**Issue by hww095** [hprose/hprose-dotnet#35]
大神，3.0版本如何编译成dll？

**Comment by andot** [comment]
https://coolcode.org/2019/02/22/how-to-compile-hprose-3.0-for-dotnet-on-vs2017/

**Comment by andot** [comment]
最新的 3.0.0-beta7 版本增加了 .NET Core 3.0 的支持，需要用 VS 2019 才能编译了。
