### ISSUE TITLE
单个方法如何设置超时时间？

### ISSUE THREAD

**Issue by hww095** [hprose/hprose-dotnet#36]
单个方法如何设置超时时间？

**Comment by andot** [comment]
因为单独为每个方法设置超时，对性能影响很大，因此在 Hprose 3.0 里面取消了对单个方法设置超时的功能。只能设置全局的超时。

**Comment by andot** [comment]
该功能已经完成。设置统一的超时，通过 client.Timeout 属性设置。设置单个调用的超时，通过 ClientContext 的 Timeout 属性设置。针对代理接口中单个方法的超时，通过在接口方法上添加 Timeout Attribute 来设置。该属性是 TimeSpan 类型的。
