### ISSUE TITLE
1.5.8 UWP调用服务方法造成未响应的问题

### ISSUE THREAD

**Issue by fenghb1911** [hprose/hprose-dotnet#40]
你好，在1.5.8版本中uwp客户端调用服务端函数，使用以下语句：
client.Invoke("Hello",new Object[]{"bbbb"})；
可以调用到server程序，但不会返回客户端调用处，且会造成uwp客户端程序未响应。
麻请问有没有解决办法？

**Comment by andot** [comment]
不要在主线程中使用同步调用。
