### ISSUE TITLE
如何使用AspNetCoreHttpHandler？

### ISSUE THREAD

**Issue by zhaxg** [hprose/hprose-dotnet#41]
能不能帮忙写点例子？谢谢

**Comment by zhaxg** [comment]
是不是自定义一个 MyHandlerMiddleware，然后再
    public static class MyHandlerExtensions
    {
        public static IApplicationBuilder UseMyHandler(this IApplicationBuilder builder)
        {
            return builder.UseMiddleware<MyHandlerMiddleware>();
        }
    }

**Comment by andot** [comment]
app.Run 的参数就是 AspNetCoreHttpHandler 的 Handler 方法。

**Comment by xgzhc** [comment]
我是这样用的，不知道对不对，不过好像可以用
` Hprose.RPC.Service.Register<Hprose.RPC.AspNetCore.AspNetCoreHttpHandler, HttpContext>("aspcore");
            Hprose.RPC.Service service = new Hprose.RPC.Service();
            service.AddStaticMethods(typeof(Busi));
            app.Run(async (context) =>
            {
                   Task task = new Task(new Action(() =>
                    {
                        service.Bind<HttpContext>(context);
                    }));
                    task.Start();
                    await task;
}
`

**Comment by andot** [comment]
可以是可以，就是你写复杂了。

```C#
using Hprose.RPC;
using Hprose.RPC.AspNetCore;

...

Service service = new Service();
service.AddStaticMethods(typeof(Busi));
AspNetCoreWebSocketHandler webSocketHandler = new AspNetCoreWebSocketHandler(service);
app.Run(webSocketHandler.Handler);
```

这样写就可以了。

使用 `AspNetCoreWebSocketHandler` 代替 `AspNetCoreHttpHandler` 可以同时支持 http 和 WebSocket 协议。

`Register` 和 `Bind` 在这里都不是必须的。

**Comment by WildShooter** [comment]
谢谢马哥，明白了
