### ISSUE TITLE
hprose client3.0如何获取http的相关状态，如状态码

### ISSUE THREAD

**Issue by WildShooter** [hprose/hprose-dotnet#42]
hprose client3.0如何获取http的相关状态，如状态码，通过请求服务，拿到服务的状态码，来验证服务是否通

**Comment by andot** [comment]
目前没有这个功能，如果需要的话，这个可以加上。

**Comment by andot** [comment]
目前 .NET 客户端可以通过返回的 context 获取这些信息。.NET CF 客户端还不支持。

**Comment by andot** [comment]
.NET CF 也支持了。通过 `context["httpStatusCode"]` 和 `context["httpStatusText"]` 可以获取到。
