### ISSUE TITLE
Hprose-java2.0版本客户端，能调用hprose-dotnet3.0服务的远程方法吗？

### ISSUE THREAD

**Issue by hww095** [hprose/hprose-dotnet#43]
Hprose-java2.0版本客户端，能调用hprose-dotnet3.0服务的远程方法吗？  
--调用hprose-dotnet1.58版本的是可以的

调用后，老是报 “远程主机强迫关闭了一个现有的连接。” 这个错。

**Comment by hww095** [comment]
这个服务端创建server的部分代码：
modID = ServerConfig.RPCServerModID;
                serverIP = ServerConfig.localIP;
                port = ServerConfig.RPCServerPort;
                IPAddress iPAddress = Dns.GetHostAddresses(serverIP)[0];
                server = new TcpListener(iPAddress, port);
                server.Start();

                //创建消息队列服务
                broker = new Broker(new Hprose.RPC.Service());
                broker.HeartBeat = TimeSpan.FromMilliseconds(10 * 1000); //该属性默认值为 3000
                //timeout 和 heartbeat 属性在检测客户端是否离线时是相互配合的，当服务器端没有向客户端推送任何消息时，服务器端需要至少 timeout +heartbeat 的时间才能检测到客户端以离线。当服务器端有向客户端推送消息时，则在推送消息之后经过 heartbeat 时间可以检测到客户端以掉线
                //属性默认值为 120000
                broker.Timeout = TimeSpan.FromMilliseconds(60 * 1000);

                rpcService = broker.Service;

                // 注册远程方法
                RegeditMethods();

                rpcService.Bind(server);

                //注册消息队列消费者
                RegisterProsumer();

**Comment by andot** [comment]
只有 http 普通的远程调用支持。

推送不支持。

**Comment by hww095** [comment]
非常感谢。
java版本3.0 大概什么时间能出来啊？

**Comment by xgzhc** [comment]
我用java2.0调用dotnet3.0一般情况没有问题，但是当java类的字段多于.net服务的字段时就会出错，好像也没有@Ignore之类的标识忽略此字段， .net服务的字段多于java客户端时也没有问题。

**Comment by andot** [comment]
xgzhc 是什么问题，能详细描述一下吗？

**Comment by xgzhc** [comment]
抱歉，今天重新测试却没有出现类似问题，晕
