### ISSUE TITLE
ioc实现hprose的注册

### ISSUE THREAD

**Issue by WildShooter** [hprose/hprose-dotnet#44]
就是我的hprose的注册，如何通过IOC容器来实现，而不是通过new这个hprose的类，来实现服务的注册

**Comment by andot** [comment]
你可以用你喜欢的任何方式来创建服务对象，不管是用 IOC 还是 new，这个跟 hprose 本身无关。

**Comment by tky753** [comment]
@andot  Service 有一个 AddInstanceMethods的方法了，这个instance是单例吧，想要结合ioc框架，每次调用都通过ioc框架初始化一个实例，再调用实例的方法，能不能达到这种效果？
现在只能搞个全局的 静态resolver，在instance的方法里 用那个来获取其他用到的组件
