### ISSUE TITLE
不知道为什么反序列化DataTable总是空的？？

### ISSUE THREAD

**Issue by Herryo0O** [hprose/hprose-dotnet#46]
不知道为什么反序列化DataTable总是空的？？

string s = "a3{c5\"Table\"5{s6\"menuId\"s8\"parentId\"s8\"menuName\"s8\"menuType\"s7\"orderBy\"}o0{s6\"MA0001\"ns4\"个人中心\"uA0}o0{s6\"MA0002\"ns4\"基础资料\"uA2}o0{s6\"MA9999\"ns2\"关于\"uAl99;}}";
            byte[] b = Encoding.UTF8.GetBytes(s);
            DataTable dt = Hprose.IO.Formatter.Deserialize<DataTable>(b);

**Comment by andot** [comment]
你没有指定反序列化的类型是 DataTable。
