### ISSUE TITLE
序列化DataTable栏位数大于9个就出错了

### ISSUE THREAD

**Issue by Herryo0O** [hprose/hprose-dotnet#48]
栏位少时正常，序列化为 a203{c5"Table"6{s5"logId"s5"level"s7"content".....

栏位数大于9个就出错了，序列化为 a1{c5"Table"i14;{s7"orderId"s7"orderNo"s7"s.....

感觉正常应该是 a1{c5"Table"14 而不是 a1{c5"Table"i14;

**Comment by andot** [comment]
确实是个 bug，明天修一下。
