### ISSUE TITLE
似乎Hprose.IO 3.0又发现问题，C#版byte[]序列化有问题

### ISSUE THREAD

**Issue by Herryo0O** [hprose/hprose-dotnet#49]
似乎Hprose.IO 3.0又发现问题，C#版byte[]序列化有问题，我不知道bug在哪里，场景是这样的：

我在服务器上做了个下载文件的RPC，每次从服务器的一个压缩文件读取100K数据byte[]返回，循环下载完后到本地，发现压缩文件损坏不能用。 但是用旧版的Hprose.IO就OK，用Newtonsoft的Json序列化也OK，所以应该是Hprose.IO 3.0 C#版byte[]序列化有问题~~

**Comment by andot** [comment]
从代码上没看出有什么问题来。
