### ISSUE TITLE
希望在 .Net 中增加对 Expression 表达式序列化的支持

### ISSUE THREAD

**Issue by Showhys** [hprose/hprose-dotnet#50]
希望在 .Net 中增加对 Expression 表达式序列化的支持,或作为插件存在,如:
  public List<T> Query<T>(**Expression**<Func<T,bool>> expr);
我希望能能序列化参数 expr.

**Comment by andot** [comment]
hprose 3.0 for .NET 支持自定义序列化和反序列化。对于这种类型你想序列化，你可以自己实现。
