### ISSUE TITLE
事务

### ISSUE THREAD

**Issue by 273168121** [hprose/hprose-dotnet#51]
可能与项目无关，core 请问能实现rpc服务调用rpc服务，就是嵌套事务差不多的功能，scope不能在core里用，

**Comment by andot** [comment]
rpc 服务调用 rpc 服务是可以做到的。hprose 不但可以 rpc 服务调用 rpc 服务，还可以服务器调用客户端发布的服务，还可以推送数据给客户端，还可以从一个客户端推送数据到另外一个或多个客户端。但我不知道你说的事务是什么。rpc 是面向动作的，事务是面向数据的，数据可以回滚，动作没法回滚。

**Comment by 273168121** [comment]
就是数据库事务，.netframwork有个transcope ,但是到了.netcore里没有，比如rpc服务方法1里有个删除datatable的操作，rpc服务方法2里有个更新datatable的操作，但是rpc2可能执行异常那rpc1能回滚删除操作吗？还是把Rpc服务方法2不标记为Rpc服务而算一个业务操作呢？

**Comment by andot** [comment]
这个我不懂

**Comment by 273168121** [comment]
谢谢你的解答

**Comment by 273168121** [comment]
还有服务端用.netcore,客户端用.net40 能和服务端交互吗？

**Comment by andot** [comment]
能的

**Comment by 273168121** [comment]
thx
