### ISSUE TITLE
DataTable序列化发现两个问题

### ISSUE THREAD

**Issue by tky753** [hprose/hprose-dotnet#66]
1. **DataTable**的**TableName** 含有 **下划线**的话会报  `给定关键字不在字典中`
2. **ColumnName**首字母反序列化时会变成小写，例如 BS_ID --> bS_ID

**Comment by andot** [comment]
第一个问题有空我看一下，第二个问题是DataTable 是按照类序列化的，类在序列化时字段首字母都转化成小写，反序列化时会把首字母再转为大写。有空看一下是不是反序列化的时候忘了转化了。
