### ISSUE TITLE
DateTime? 无法提交给接口

### ISSUE THREAD

**Issue by lihaoru** [hprose/hprose-dotnet#71]
参数如果是DateTime?参数，好像不管是null或是有值的参数Client端都会报错

**Comment by andot** [comment]
Nullable<DateTime> 这个类型是有实现的，或者说所有的 Nullable<T> 类型都有实现序列化和反序列化的，你遇到的是什么错误？

**Comment by lihaoru** [comment]
我定义了个类
public class TestInfo
    public int id { get; set; }
    public DateTime starttime { get; set; }

在接口中定义int AddTest(TestInfo item); 远端调用没有问题，也能返回正确的结果

但是如果我把DateTime改成DateTime?

编译也都能通过 但是Client调用时会报错 Server端无法收到任何信息

错误信息如下：
System.Exception:“找不到方法:“System.DateTime LJT_Model.TestInfo.get_connecttime()”。”

**Comment by andot** [comment]
错误是找不到你调用的那个方法。
