### ISSUE TITLE
有没有办法用于 Anonymous pipes 和 Named pipes （进程间通信）

### ISSUE THREAD

**Issue by tky753** [hprose/hprose-dotnet#72]
父进程和子进程之间通信，不想开个端口，走TCP通信，用 系统提供的管道来通信，一边传一个Stream，另一边接收这个Stream。
请求等待响应可能有些麻烦，不等待响应，是否可以用hprose来处理

**Comment by andot** [comment]
我没试过，你可以参考：
https://github.com/hprose/hprose-dotnet/blob/master/src/Hprose.RPC/TcpHandler.cs
https://github.com/hprose/hprose-dotnet/blob/master/src/Hprose.RPC/TcpTransport.cs
这俩试试看。

TcpHandler 是服务器端的 Tcp 处理代码，TcpTransport 是客户端的 Tcp 处理代码。你按照这个结构来分别写一个 pipes 的客户端和服务器端处理代码，然后 

```c#
Client.Register<AnonymousPipeTransport>("ap");
Client.Register<NamedPipeTransport>("np");
Service.Register<AnonymousPipeHandler, AnonymousPipeServerStream>("ap");
Service.Register<NamedPipeHandler, NamedPipeServerStream>("np");
```

注册一下你开发的这些处理代码就可以用了。

**Comment by tky753** [comment]
整了两天半，终于粗略能用了。
服务端我没有用Handler，有一个Service，然后封装它的Handle方法，就OK了。
客户端还是要老老实实实现Transport，不过还是很简单的，传入PipeStream，然会对这个Stream进行输入输出。是的，输出也封装了，因为用的NamedPipeStream 本身就是双向流，这样Request - Response模式也搞定了。
还有一个难点在于服务端也可以向客户端发起请求，所以单个Stream是不够的，因此整了两个Stream，终于是简单测试通过了。

不得不说，Hprose的API封装的太好了，所有针对liu的传输都可以轻易嫁接上。真棒👍
