### ISSUE TITLE
服务端asp.net,客户端winform,使用反向调用,Server不停报错 引发的异常:“System.Exception”(位于 Hprose.RPC.dll 中)

### ISSUE THREAD

**Issue by huoxin2008** [hprose/hprose-dotnet#77]
2个端的版本一样
Hprose.RPC.3.0.18\lib\net452\Hprose.RPC.dll
Hprose.IO.3.0.19\lib\net452\Hprose.IO.dll
Hprose.RPC.Plugins.3.0.18\lib\net452\Hprose.RPC.Plugins.dll
Hprose.RPC.AspNet.3.0.18\lib\net452\Hprose.RPC.AspNet.dll

只有dll,没下载源码,只能看到这样的提示
引发的异常:“System.Exception”(位于 Hprose.RPC.dll 中)

**Comment by andot** [comment]
解决了？

**Comment by huoxin2008** [comment]
解决了,原因是,Provider在的Caller 生成之前调用,不停报 找不到 !! 的方法错误,调试源代码才看到的,只引用dll看不到具体错误信息
比如&nbsp;
服务端 invoke(){
&nbsp; new Caller().invoke()
}
客户端
程序启动时
new Provider().Listen()






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "小马哥"<notifications@github.com&gt;; 
发送时间: 2021年1月5日(星期二) 中午1:35
收件人: "hprose/hprose-dotnet"<hprose-dotnet@noreply.github.com&gt;; 
抄送: "也许有"<402885727@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [hprose/hprose-dotnet] 服务端asp.net,客户端winform,使用反向调用,Server不停报错 引发的异常:“System.Exception”(位于 Hprose.RPC.dll 中) (#77)





 
解决了？
