### ISSUE TITLE
TCP 超时原因请分析一下

### ISSUE THREAD

**Issue by zzdwsourcesafe** [hprose/hprose-dotnet#81]
上传失败!!!   在 Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   在 Microsoft.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 COMM.frmMain.<SendToRPC>d__10.MoveNext() 位置 D:\Visual Studio 2021\RPCRainfalls\COMM\frmMain.cs:行号 142
上传失败!!!   在 Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   在 Microsoft.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 COMM.frmMain.<SendToRPC>d__10.MoveNext() 位置 D:\Visual Studio 2021\RPCRainfalls\COMM\frmMain.cs:行号 142

Code:
try
            {
                var client = new Client("tcp://127.0.0.1:8412");
                var result = await client.InvokeAsync<bool>("RPCAcceptRain", new object[] { jsonString });
            }
            catch (Exception e)
            {
                Console.WriteLine(string.Format("上传失败!!!" + e.StackTrace));
            }

**Comment by zzdwsourcesafe** [comment]
敢不敢出篇文档啊

**Comment by andot** [comment]
不敢啊
